gui:
  scrollHeight: 16
  theme:
    activeBorderColor:
      - "#31748f"
      - bold
    inactiveBorderColor:
      - "#6e6a86"
    searchingActiveBorderColor:
      - "#ebbcba"
      - bold
    optionsTextColor:
      - "#9ccfd8"
    selectedLineBgColor:
      - "#31748f"
    inactiveViewSelectedLineBgColor:
      - "#26233a"
      - bold
    cherryPickedCommitFgColor:
      - "#1f1d2e"
    cherryPickedCommitBgColor:
      - "#ebbcba"
    markedBaseCommitFgColor:
      - "#9ccfd8"
    markedBaseCommitBgColor:
      - "#f6c177"
    unstagedChangesColor:
      - "#eb6f92"
    defaultFgColor:
      - "#e0def4"
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never
customCommands:
  - key: "<c-r>"
    command: "git branch --set-upstream-to=origin/mainline && cr --publish --auto-merge"
    context: "global"
    output: log
