return {
	"jakewvincent/mkdnflow.nvim",
	ft = { "markdown" },
	opts = {
		modules = {
			bib = false,
			buffers = false,
			conceal = false,
			cursor = true,
			folds = false,
			foldtext = false,
			links = true,
			lists = true,
			maps = true,
			paths = true,
			tables = true,
			templates = false,
			to_do = true,
			yaml = false,
			completion = false,
			notebook = false,
			backlinks = false,
		},
		to_do = {
			statuses = {
				complete = { marker = { "x", "X" } },
			},
		},
		mappings = {
			MkdnEnter = { "i", "<CR>" },
			MkdnNewListItem = false,
			MkdnNewListItemBelowInsert = { "n", "o" },
			MkdnNewListItemAboveInsert = { "n", "O" },
			MkdnToggleToDo = { { "n", "v" }, "<Leader>lx" },
			MkdnUpdateNumbering = { "n", "<Leader>nn" },
			MkdnFollowLink = { "n", "gx" },
			MkdnNextHeading = { "n", "]]" },
			MkdnPrevHeading = { "n", "[[" },
			MkdnIncreaseHeading = { { "n", "v" }, "+" },
			MkdnDecreaseHeading = { { "n", "v" }, "-" },
			MkdnIndentListItem = { "i", "<C-t>" },
			MkdnDedentListItem = { "i", "<C-d>" },
			MkdnGoBack = false,
			MkdnGoForward = false,
			MkdnMoveSource = false,
			MkdnNextLink = false,
			MkdnPrevLink = false,
			MkdnDestroyLink = false,
			MkdnTagSpan = false,
			MkdnYankAnchorLink = false,
			MkdnYankFileAnchorLink = false,
			MkdnNextHeadingSame = false,
			MkdnPrevHeadingSame = false,
			MkdnIncreaseHeadingOp = false,
			MkdnDecreaseHeadingOp = false,
			MkdnTableNextCell = false,
			MkdnTablePrevCell = false,
			MkdnTableCellNewLine = false,
			MkdnTablePrevRow = false,
			MkdnTableNewRowBelow = false,
			MkdnTableNewRowAbove = false,
			MkdnTableNewColAfter = false,
			MkdnTableNewColBefore = false,
			MkdnTableDeleteRow = false,
			MkdnTableDeleteCol = false,
			MkdnTableAlignLeft = false,
			MkdnTableAlignRight = false,
			MkdnTableAlignCenter = false,
			MkdnTableAlignDefault = false,
			MkdnFoldSection = false,
			MkdnUnfoldSection = false,
			MkdnCreateLinkFromClipboard = false,
		},
	},
}
